# https://github.com/probot/stale

daysUntilStale: 180
daysUntilClose: 90

exemptLabels:
  - 'priority: critical'
  - 'type: maintenance'

staleLabel: 'status: abandonded'

markComment: >
  This issue has been marked stale/abandoned. It will automatically be closed 90 days from now unless updated.

unmarkComment: false
closeComment: false
