# https://github.com/probot/stale

daysUntilStale: 90
daysUntilClose: 30

exemptLabels:
  - 'priority: critical'

staleLabel: 'status: abandonded'

markComment: >
  This issue has been marked stale/abandoned. It will automatically be closed 30 days from now unless updated.

unmarkComment: false
closeComment: false
